### ISSUE TITLE
Мимикрия должна работать раз в ход, а не раз в раунд

### ISSUE THREAD

**Issue by ivan-work** [ivan-work/evolution-web#10]
### Мимикрия

По правилам она действует только один раз в ход. Но игра позволяет это делать несколько раз.
и в догонку. Интерфейс игры не отрисовывает накормленность животных при мимикрии. В результате игроку трудно понять перенаправляет он атаку на голодное или на накормленное существо.

Ход - это вся фаза питания. Впечатление, что у мимикрии нет ограничений вероятно осталось со второй редакции правил в 2012 году.

Мимикрия действовала всегда в I и II редакции до 2012 года.

В 2012 году вышла III редакция (где-то в промежутке между мартом 2012 и ноябрем 2012. Скорее всего в октябре). 

Там мимикрия уже действовала 1 раз в ход.

А также в последующих редакциях: "подарочный набор" 1.3.2 2014 год" и 1.4.1 2015 года

![mimicry](https://user-images.githubusercontent.com/8690724/84392045-7d47f000-ac02-11ea-80fe-2ab43a7f0490.jpg)

**Comment by evoguest** [comment]
В текущей реализации мимикрия работает фактически непрерывно, что делает ее непреодолимой защитой. Всякий смысл нападения на мимикрию теряется.

**Comment by ivan-work** [comment]
Добавлено в 1.1.4
