### ISSUE TITLE
FR: обновление правил до последней версии

### ISSUE THREAD

**Issue by banderlog** [ivan-work/evolution-web#12]
Добрый день,

Спасибо, отличная игра :)

Планируется в дальнейшем обновление правил с [III редакции (ноябрь 2012)](https://vk.com/doc-36567706_134818567) до [v1.4.1 (июнь 2015)](http://rightgames.ru/sites/default/files/evo-rules-baseset-148x195-ru_scr.pdf)?

**Comment by ivan-work** [comment]
Привет, спасибо.

В теории уже сейчас поддерживается последняя версия правил (1.4.1). А какие у них отличия?

**Comment by banderlog** [comment]
Кажется, я опростоволосился)

Я искренне считал, что авторы вносили какие-то изменения в свойства животных, но они только исправляли опечатки и меняли вординг. Так что все актуальнее некуда)
