### ISSUE TITLE
Спячка накормленного с незаполненным жиром

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#123]
Игра позволяет уйти в спячку накормленному животному с незаполненным жиром. (т.е. свойство спячка подсвечивается зеленым).Даже не только позволяет, но и ждет пока ты не нажмешь закончить фазу.
Однако я не вижу ни одной игровой ситуации, когда бы это было полезно. 
Разве что такую чисто теоретическую и маловероятную хитрую стратегию, когда тебе надо, чтобы твой соперник после тебя выжил (поел), но если ты поешь, то он ему не хватит еды, поэтому ты входишь в спячку и намеренно блокируешь себе возможность поесть.
Предлагаю отключить возможность уйти в сон при накормленности независимо от наполнения жира.

**Comment by ivan-work** [comment]
не, если правила позволяют, то и игра позволяет
