### ISSUE TITLE
Парочка мест без перевода на английский

### ISSUE THREAD

**Issue by Rinkaru** [ivan-work/evolution-web#125]
В первую очередь хочу сказать огромное спасибо за перевод <З

Наткнулась на парочку мест отображающихся в интерфейсе без перевода: 

1. Окошко подтверждения начала игры
 ![Screenshot 2021-08-06 at 21-06-18 Evolution](https://user-images.githubusercontent.com/13394052/128558580-66e9b627-9ab4-4030-8145-96d770810b6e.png)
2. Лог игры
 ![Screenshot 2021-08-06 at 21-21-23 Evolution](https://user-images.githubusercontent.com/13394052/128558584-0cab28c2-9e3a-4008-8f85-c941c39add26.png)
3. Подпись к иконке лога игры
<img width="384" alt="Screenshot 2021-08-06 at 21 57 18" src="https://user-images.githubusercontent.com/13394052/128558929-896f7cde-f9ec-458f-9d22-17b1bb7f55b4.png">
4. Системные сообщения в чате

![image](https://user-images.githubusercontent.com/13394052/128559722-3d88782f-4e94-47fa-9d61-e9b67e38c3a4.png)

5. После окончания игры кнопка "Счёт"
![image](https://user-images.githubusercontent.com/13394052/128559323-8dba2a2e-7086-46a6-b01d-a810279132e6.png)

6. Описания наборов карт
<img width="555" alt="Screenshot 2021-08-06 at 22 08 53" src="https://user-images.githubusercontent.com/13394052/128560411-87e2e67c-4336-4ca1-ad11-1076cc15560b.png">

7. Карты растений
![Screenshot 2021-08-06 at 22-10-13 Evolution](https://user-images.githubusercontent.com/13394052/128560551-0e448141-2bb7-4db0-9377-3cc40a97aa8c.png)

![Screenshot 2021-08-06 at 22-12-40 Evolution](https://user-images.githubusercontent.com/13394052/128560613-e4081c0d-d561-48b3-937f-ac64d861ab71.png)

**Comment by ivan-work** [comment]
Fixed in 1.1.7
