### ISSUE TITLE
Таймер последних секунд

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#23]
- [ ] Предлагается сделать звук таймера последних 10 секунд немного потише. Цель звука обратить внимание игрока на время, а не мешать ему думать.
- [ ] Если время хода выставлено 15 секунд и меньше, то предлагается сделать звук отчета не на последних 10 секундах, а на последних 5 или 3 секундах. Если от 15 до 20 секунд, то звук начиная с 8-й секунды. Более 20 секунд - как обычно, начиная с 10й секунды.

**Comment by ivan-work** [comment]
1. Немного потише это сколько?) 
2. Слишком сложная логика / будет сбивать привычку / я бы не рекомендовал ставить 15 сек или меньше. Вдруг у человека залагает что-то или интернет глюканет.

**Comment by evoguest** [comment]
1. На 15 дБ.
2. Я играю 15-20 секунд. И как ты понимаешь играю не сам с собой ) Получаются отличные, динамичные игры! В шахматах же есть режим пуля: чем Эволюция хуже? Только сейчас это тиканье немного давит на мозги.

**Comment by ivan-work** [comment]
1. сейчас 60% от оригинала. Сделать 30%?
2. я сделаю так - если время меньше 30 секунд - звука отсчета просто не будет

**Comment by evoguest** [comment]
1. Если можно, то примерно 40%
2. Я думаю, что последние 5 секунд отсчитывать можно. Но если совсем убрать, начиная с 25 секунд, то это лучше чем сейчас.

**Comment by ivan-work** [comment]
v1.1.5
