### ISSUE TITLE
Удильщик сохраняет интеллект

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#53]
Если контр-атака удильщика была перенаправлена с помощью мимикрии на стрекательные клетки, то у хищника-удильщика сохранится интеллект.
В следующем ходу возможно использовать вкрытого удильщика как обычного хищника с интеллектом.
Важна последовательность действий. Сначала удильщик должен быть перенаправлен, а потом получить стрекательные клетки, иначе баг не проявится.
```
phase: feeding
players:
- continent: carn mimi mass, cni, Anglerfish
```

**Comment by ivan-work** [comment]
пофикшено в https://github.com/ivan-work/evolution-web/pull/137
