### ISSUE TITLE
Зайти в начатую игру

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#69]
Добавить опцию на окне создания игры "Разрешать присоединяться зрителям"
При активированной опции зритель может сделать запрос на присоединение к игре. 
Всем игрокам придется запрос: разрешить/не разрешать. Если все игроки разрешают, то в ближайший новый ход зритель присоединяется последним в кругу и ему выдается столько карт, сколько наименьшее количество на руке+на столе у любого из игроков, но не более 6.

Каждый зритель может сделать не более 2 запросов за игру. Нельзя присоединяться, если отыграно более половины колоды.

Запросы можно реализовать кнопками или командами в чате.

Сценарий, когда кто-то не успел буквально 1-2 хода после начала игры довольно частая.

**Comment by ivan-work** [comment]
Считаю feature creep. Если буквально 1-2 хода, то можно просто начать заново.

**Comment by evoguest** [comment]
думаю, что фича будет пользоваться бешеной популярностью
