### ISSUE TITLE
Примерное время игры

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#74]
На экране создания игры в добавить автоматически генерируемую сноску: Примерное время игры xxx минут.
Это позволит игрокам лучше ориентироваться в том сколько займет игра.
Оценивать время по 3 параметрам: время хода, количество карт, количество игроков. В более продвинутой версии можно также учитывать наличие/отсутствие дополнения "растения".
Необходимо придумать формулу.
Пока игра не собирает статистику предлагаю следующее:
0,5, 84, 4 -- 20 минут
0,5, 120, 4 -- 30 минут
0,5, 140, 5 - 40 минут
0,5, 166, 6 - 50 минут
0,5, 166, 7/8 - 1 час+
1, 166, 7/8 - 1 час 10 минут
2, 166, 7/8 - 2 часа
0.25, 166, 5 - 30 минут

**Comment by ivan-work** [comment]
Считаю feature creep
