### ISSUE TITLE
Приватные чаты

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#76]
Реализовать возможность писать адресные сообщения в общем игровом чате.
Например, кодовым словом
`to Vituk` Enter
все ваши сообщения видит только Vituk
`to all` Enter
все ваши сообщения видят все

Это очень нужно в парных играх типа 2x2. -- этот форма игры имеет заметное число любителей.

Запретить писать адресные сообщения наблюдателям.

**Comment by ivan-work** [comment]
Изначально так и хотел сделать, но потом понял, что функцию приватных сообщений отлично выполняют сторонние программы.

Не думаю, что они будут удобнее чем каждый раз менять раскладку и писать /m Vituk или же просто выписывать /м Степан Алексеевич

**Comment by evoguest** [comment]
большинство из нас все-таки не знакомы друг с другом и не имеет сторонних каналов связи.
Я вот не знаю никого из тех, кого вижу чуть ли не каждый день.
И я все-таки думал не на каждое сообщение писать "to Vituk", а только один раз. По типу открытия/закрытия тега.

**Comment by ivan-work** [comment]
Я на 100% уверен, что приложение должно качественно выполнять 1 функцию - позволять людям играть в "настольную" эволюцию в онлайне. Остальные функции она должна выполнять по минимуму.

А то так можно дойти и до feature "добавить тетрис в комнату ожидания, чтобы люди не скучали пока ждут".

Так что считаю, что делать функции которые легко заменяются аналогами неправильно.
