### ISSUE TITLE
Пропуск хода во время фазы развитие

### ISSUE THREAD

**Issue by allikhachev** [ivan-work/evolution-web#8]
Иногда один из игроков не может использовать карты во время фазы развитие. Карты неактивны. Не выполняется переключение после выкладывания карты противником.
Игра на 2 игровка

**Comment by ivan-work** [comment]
Если игрок спасовал, то больше он не может выкладывать карты. + нужен лог

**Comment by allikhachev** [comment]
Спасибо за разъяснения.
Попробую воспроизвести. Возможно я действительно нажал на "закончить фазу"
