### ISSUE TITLE
Метаморфоза трематоды

### ISSUE THREAD

**Issue by Viktor-lashin** [ivan-work/evolution-web#80]
Когда одно из существ было подвергнуто воздействию стрекательных клеток, тогда второе существо может сбросить трематоду при помощи метаморфозы. Баг обнаружен игроком сухарик_47 и проверен игроком Vituk

**Comment by evoguest** [comment]
Это не баг. Я писал о нем в августе [в ветке с Юрием](https://vk.com/topic-36567706_26132044?post=6812). Если трематода отключена, то все, что написано на карте трематоды, - не действует.
