### ISSUE TITLE
Подсказка для автовыбора защиты

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#83]
Когда идет атака и тикает таймер реагирования на атаку предлагаю внизу под карточками разместить надпись
`Если игрок не сделает выбор, то автоматически будет активировано свойство <>.`
На сколько я понимаю в текущей логике игра автоматически выбирает первое снизу защитное свойство животного (за исключением ядовитого, которое является пассивным) .

**Comment by ivan-work** [comment]
Лишний функционал. В нормальной игре игрок сам выбирает. Как максимум можно дописать в хелпу/гайд, но планов её сделать пока нет
